package items;

public enum ItemID {
	WOODEN_SWORD, IRON_SWORD, DIAMOND_SWORD, 
	LEATHER_ARMOR, IRON_ARMOR, DIAMOND_ARMOR,
	SMALL_POTION, MEDIUM_POTION, LARGE_POTION,
	KEY, BROAD_SWORD, GREAT_SWORD

}
